config/routes.rb
Rails.application.routes.draw do

  resources :widgets

  get '/party/:id', :to => "rooms#party", :as => :party

  post '/rate' => 'rater#create', :as => 'rate'
  root :to => 'home#index'
  resources :carts, :home, :categories, :banners, :orders, :rooms

  resources :products do
    resources :images do
      collection do
        get :image_destroy
      end
    end
    resources :reviews
    resources :videos do
      collection do
        get :video_destroy
      end
    end
    member do
      get :add_to_cart
    end
  end

  resources :conversations do
    resources :chats
  end

  resources :messages do
    collection do
      get :inbox, :outbox
    end
  end
  devise_for :users

  get '/setting/:id' => 'home#setting', :as => :setting
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/contact_us' => 'home#contact_us', :as => :contact_us
  get '/services' => 'home#services', :as => :services
  put '/update_setting/:id' => 'home#update_setting', :as => :update_setting
  put '/change_password/:id' => 'home#change_password', :as => :change_password
  get '/order/express' => 'orders#express', :as => :pay
  post '/payu_callback'=>'carts#payu_return'

end

app/models/product.rb
class Product < ActiveRecord::Base
  ratyrate_rateable 'rating'
  belongs_to :category
  belongs_to :user
  has_many :images, :as => :imageable
  has_many :videos, :as => :videoable
  has_many :line_items
  has_many :reviews, dependent: :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if => :all_blank

  validates :title, :description, :category_id, :quantity, :price, :presence => true
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_attached_file :video
  validates_attachment_content_type :video,
    :content_type => ['video/mp4','video/x-flv','video/mpeg','video/ogg','video/ogv','video/mkv','video/3gpp','video/webm']

  belongs_to :videoable, :polymorphic => true

  def to_video_upload
    {
      "url" => video.url,
      "medium_url" => video.url(:medium)
    }
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @product = Product.find(params[:product_id])
    @videos = @product.videos.paginate :page => params[:video_page], :per_page => 6
  end

  def new
    @product = Product.find(params[:product_id])
    @video = @product.videos.new
  end

  def create
    @product = Product.find(params[:product_id])
    @video = @product.videos.new(new_params)
    if @video.save
      render json: { message: "success" }, :status => 200
    else
      render json: { error: @video.errors.full_messages.join(',')}, :status => 400
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @video = Video.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @video = Video.find(params[:id])
    if @video.update_attributes(new_params)
      redirect_to product_videos_path(@product)
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @video = Video.find(params[:id])
    @videos = @product.videos.all
    @video.destroy
    respond_format
  end

  def video_destroy
    @product = Product.find(params[:product_id])
    if params[:video_ids].present?
      @videos = Video.find(params[:video_ids])
      for video in @videos
        video.destroy
      end
    end
    redirect_to product_videos_path(@product)
  end

  private

  def new_params
    params.require(:video).permit!
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_videos.html.erb
<div id="pagination">
  <%= will_paginate @videos, :page_links => false, :param_name => 'video_page', :previous_label => "PREV", :next_label => "NEXT" %>
</div>
<div class="row">
  <% for video in @videos %>
    <div class="col-sm-4 col-lg-3 col-md-4">
      <div class="thumbnail">
        <span id="product_img"><%= video_tag video.video.url, :height => 185, :width => "100%", :id => "video_#{video.id}", :class => 'video', :controls => true %></span>
        <div class="ratings">
          <% if current_user %>
            <hr />
            <p>
            <div class="checkbox checkbox-danger checkbox-inline">
              <%= check_box_tag 'video_ids[]', video[:id], false,:class => 'check_all' %>
              <label for="checkbox6"></label>
            </div>|
            <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_product_video_path(video.videoable, video) %> |
            <%= link_to image_tag("rotate.jpeg"), "#", :class => "item-3", :id => "rotate_#{video.id}", :title => 'rotate' %> |
            <%= link_to "<i class='fa fa-trash-o'></i>".html_safe, product_video_path(video.videoable,video), :method => :delete, :data => { :confirm => 'Are you sure?'}, :remote => true %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <script>
      var value_<%= video.id %> = 0
      $("#rotate_<%= video.id %>").click(function() {
        value_<%= video.id %> += 90;
        $("#video_<%= video.id %>").rotate({animateTo: value_<%= video.id %>})
      });
    </script>
  <% end %>
</div>

app/views/videos/destroy.js.erb
$("#product_videos").html('<%= escape_javascript render :partial => "videos" %>');

app/views/videos/edit.html.erb
<%= form_for @video, :url => product_image_path(@product, @video), :method => 'PUT' do |f| %>
  <h3>Crop Image
    <%= f.submit 'Save', :class => 'btn btn-xs btn-success', :style => "float: right;" %>
  </h3>
  <hr />
  <%= f.cropbox :video, :width => 300 %>
  <%= f.crop_preview :video, :width => 150 %>
  <br />
<% end %>

app/views/videos/index.html.erb
<%= form_tag video_destroy_product_videos_path(@product), :method => :get do %>
  <h3>
    Product Videos
    <div class="pull-right">
      <div class="checkbox checkbox-danger checkbox-inline">
        <input type="checkbox" id="selecctall" />
        <label for="inlineCheckbox2"></label>
      </div>
      <%= submit_tag "delete all", :class => "btn btn-xs btn-danger" %>
      <%= link_to "Add Videos", new_product_video_path(@product), :class => 'btn btn-success btn-xs' %>
    </div>
  </h3>
  <hr />
  <div id="product_videos">
    <%= render :partial => 'videos' %>
  </div>
<% end %>
<script>
  $(".fancybox").fancybox();

  $("#selecctall").change(function() {
    $(".check_all").prop('checked', $(this).prop("checked"));
  });
</script>

app/views/videos/new.html.erb
<h3>Upload videos
  <%= link_to "Product videos", product_videos_path(@product), :class => 'btn btn-success btn-xs', :style => 'float: right;' %>
</h3>
<hr />
<%= form_for @video, :url => product_videos_path(@product), :method => 'POST', html: { multipart: true, class: "dropzone"} do |f|  %>
    <div class="fallback">
      <%= f.file_field :video %><br>
      <%= f.submit "Upload" %>
    </div>
  <% end %>
  <br>
  <script>
    $(document).ready(function() {
      // disable auto discover
      Dropzone.autoDiscover = true;
      // grap our upload form by its id
      $("#new_video").dropzone({
        // restrict video size to a maximum 1MB
        maxFilesize: 50,
        // changed the passed param to one accepted by
        // our rails app
        paramName: "video[video]",
        addRemoveLinks: true
      });
    });
  </script>