config/routes.rb
Rails.application.routes.draw do

  resources :widgets

  get '/party/:id', :to => "rooms#party", :as => :party

  post '/rate' => 'rater#create', :as => 'rate'
  root :to => 'home#index'
  resources :carts, :home, :categories, :banners, :orders, :rooms

  resources :products do
    resources :images do
      collection do
        get :image_destroy
      end
    end
    resources :reviews
    resources :videos do
      collection do
        get :video_destroy
      end
    end
    member do
      get :add_to_cart
    end
  end

  resources :conversations do
    resources :chats
  end

  resources :messages do
    collection do
      get :inbox, :outbox
    end
  end
  devise_for :users

  get '/setting/:id' => 'home#setting', :as => :setting
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/contact_us' => 'home#contact_us', :as => :contact_us
  get '/services' => 'home#services', :as => :services
  put '/update_setting/:id' => 'home#update_setting', :as => :update_setting
  put '/change_password/:id' => 'home#change_password', :as => :change_password
  get '/order/express' => 'orders#express', :as => :pay
  post '/payu_callback'=>'carts#payu_return'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, :dependent => :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :is_login?

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :action => 'new'
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit!
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-body">
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@category[:name]) %>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    categories_path, :class => 'btn btn-default' %>

<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_category_path, :class => 'btn btn-primary', :style => 'float: right; position: relative; top: -35px;' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>