config/routes.rb
Rails.application.routes.draw do

  resources :widgets

  get '/party/:id', :to => "rooms#party", :as => :party

  post '/rate' => 'rater#create', :as => 'rate'
  root :to => 'home#index'
  resources :carts, :home, :categories, :banners, :orders, :rooms

  resources :products do
    resources :images do
      collection do
        get :image_destroy
      end
    end
    resources :reviews
    resources :videos do
      collection do
        get :video_destroy
      end
    end
    member do
      get :add_to_cart
    end
  end

  resources :conversations do
    resources :chats
  end

  resources :messages do
    collection do
      get :inbox, :outbox
    end
  end
  devise_for :users

  get '/setting/:id' => 'home#setting', :as => :setting
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/contact_us' => 'home#contact_us', :as => :contact_us
  get '/services' => 'home#services', :as => :services
  put '/update_setting/:id' => 'home#update_setting', :as => :update_setting
  put '/change_password/:id' => 'home#change_password', :as => :change_password
  get '/order/express' => 'orders#express', :as => :pay
  post '/payu_callback'=>'carts#payu_return'

end

app/models/product.rb
class Product < ActiveRecord::Base
  ratyrate_rateable 'rating'
  belongs_to :category
  belongs_to :user
  has_many :images, :as => :imageable
  has_many :videos, :as => :videoable
  has_many :line_items
  has_many :reviews, dependent: :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if => :all_blank

  validates :title, :description, :category_id, :quantity, :price, :presence => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :add_to_cart]
  before_filter :is_login?, :except => [:add_to_cart]
  respond_to :html

  def index
    @products = Product.where(user_id: current_user.id).paginate :page => params[:product_page], :per_page => 6
    respond_with(@products)
  end

  def show
    @product = Product.find(params[:id])
    @review = @product.reviews.new
    @reviews = @product.reviews
  end

  def new
    @product = Product.new
    1.times {@product.images.build}
    respond_with(@product)
  end
  
  def add_to_cart
    @cart = current_cart
    @cart.update_attribute(:created_at, Time.now)
    session[:cart] = @cart.id
    @cart_error = "<span id='success' style='color: red;'>Sorry we are currently out of stock.</span>".html_safe
    @cart_success = "<span id='success' style='color: green;'>item successfully added to the Cart!</span>".html_safe
    @lineitem = LineItem.find_by_cart_id_and_product_id(@cart.id,@product.id)
    if !@lineitem.present?
      @success = @cart_success
      LineItem.create(:product_id => @product.id, :quantity => 1, :unit_price => @product.price, :cart_id => @cart.id)
    else
      if @lineitem.quantity < @product.quantity
        @success = @cart_success
        @lineitem.update_attribute(:quantity, @lineitem.quantity + 1)
      else
        @success = @cart_error
      end
    end
    respond_format
  end

  def edit
  end

  def create
    @product = Product.new(product_params.merge(user_id: current_user.id))
    1.times{@product.images.build} if @product.images.blank?
    if @product.save
      respond_with(@product)
    else
      render :action => 'new'
    end
  end

  def update
    if @product.update(product_params)
      respond_with(@product)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit!
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= nested_form_for @product, :html => { :class => "form-horizontal product" } do |f| %>
<div class="col-md-5">
  <%= render :partial => '/layouts/error_messages', :locals => {:resource => @product} %>

  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <%= f.select :category_id, options_for_select([["Select",nil]]+Category.all.map{|a| [a.name, a.id]}, :selected => f.object.category_id),{}, :class => 'form-control' %>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:title]) %>
  </div>  
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :price, min: 1, :class => 'form-control' %>
    </div>
    <%= error_span(@product[:price]) %>
  </div>
  <div class="control-group">
    <%= f.label :quantity, :class => 'control-label' %>
    <%= f.number_field :quantity, min: 1, :class => 'form-control' %>
  </div>  
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls emoji-picker-container">
      <%= f.text_area :description, cols: 50, rows: 3, :class => 'form-control', data: {emojiable: true} %>
    </div>
    <%= error_span(@product[:description]) %>
  </div>
  <div class="control-group col-md-9">
    Image
    <%= f.fields_for :images do |builder| %>      
    <%= builder.file_field :image %>
    <br>
    <%= builder.link_to_remove "Remove".html_safe, :class => 'btn btn-danger btn-xs pull-right', style: 'margin-top: -45px;' %>      
    <% end %>
  </div>
  <div class="control-group col-md-9">
    <div class="controls"><%= f.link_to_add "Add+".html_safe, :images, :class => 'btn btn-success btn-xs' %></div>
  </div>
  <div class="control-group col-md-9">
    <%= f.submit "Save", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn btn-default' %>
  </div>
</div>
<% end %>

app/views/products/_index.html.erb
<div id="pagination">
  <%= will_paginate @products, :page_links => false, :param_name => 'product_page', :previous_label => "PREV", :next_label => "NEXT" %>
</div>
<div class="row">
  <% if @products.present? %>
  <% for product in @products %>
  <div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
      <span id="product_img"><%= link_to image_tag(product.images.first.image.url(:original)), product_path(product) %></span>
      <div class="caption">
        <h4 class="pull-right"><%= number_to_currency(product.price) %></h4>
        <h4><%= link_to product.title, product_path(product) %>
        </h4>        
        <%= (current_user && product.user_id != current_user.id) ? (link_to "<span class='fa fa-thumbs-up'></span>".html_safe, "#", class: 'pull-left') : "" %>
        <%= (current_user && product.user_id != current_user.id) ? (link_to "<span class='fa fa-comments'></span>".html_safe, "#", class: "start-conversation pull-right", "data-sid" => current_user.id, "data-rip" => product.user.id) : "" %>
      </div>
      <div class="ratings">
        <p class="pull-right"><%= product.quantity != 0 ? (link_to "Add to Cart", add_to_cart_product_path(product), :remote => true, :class => 'btn btn-success btn-xs') : (link_to "Sold Out", "", :class => 'btn btn-danger btn-xs') %> </p>
        <p><%= rating_for product, "rating", disable_after_rate: true, cancel_place: 'right', space: true %></p>
        <% if current_user && product.user_id == current_user.id %>
        <hr />
        <p class="pull-right"><%= link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %></p>
        <p><%= link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-warning btn-xs' %></p>
        <p class="pull-right"><%= link_to "Videos", product_videos_path(product), :class => 'btn btn-warning btn-xs', :class => 'btn btn-warning btn-xs' %></p>
        <p><%= link_to "Images", product_images_path(product), :class => 'btn btn-warning btn-xs', :class => 'btn btn-warning btn-xs' %></p>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
  <% else %>
  <span> No Products </span>
  <% end %>
</div>

app/views/products/add_to_cart.js.erb
$("#items_count").html(<%= current_cart.line_items.count %>).css("color", "white");
$("#cart").html('<%= escape_javascript render :partial => '/layouts/cart' %>');

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<div class="page-header">
  <h3>Products
    <%= link_to "New Product", new_product_path, :class => 'btn btn-xs btn-success pull-right' %>
  </h3>
</div>

<%= render :partial => 'index' %>

app/views/products/index.js.erb
$("#products").html('<%= escape_javascript render :partial => '/products/index' %>');
$('.pagination a').attr('data-remote', 'true');

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<section class="col-sm-9 col-md-9 col-lg-9 col-xs-12">
  <h1><%= @product.title.html_safe %></h1>
  <div class="ccrow">
    <div class="col-sm-4 col-md-4 col-lg-4">
      <div class="leftColumn-flowers">
        <ul class='bxslider'>
          <% for image in @product.images %>
          <li><%= link_to image_tag(image.image.url(:original), :style => 'border-radius: 3px;'), "#{image.image.url}", :title => "#{image.image_file_name}", :class => 'fancybox', :rel => "gallery1" %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
      <div>
        <p>Price: <%= number_to_currency(@product.price) %></p>
      </div>
    </div>
  </div>
  <b>Product Details:</b>
  <br />
  <p><%= content_with_emoji(@product.description.html_safe) %></p>   
</section>
<div class="col-md-12">
  <%= form_for(:review, url: product_reviews_path(@product), remote: true) do |f| %>
  <div class="control-group">
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
    <%= f.text_field :comment, :class => 'form-control' %>
    </div><br />
    <%= f.submit "Comment", :class => 'btn btn-primary' %>
  </div>
  <% end %> 
  <div class="page-header">
    <h1><small class="pull-right"><%= @reviews.count %> comments</small> Comments </h1>
  </div> 
  <div class="comments-list">
    <%= render :partial => "/reviews/comment" %>
  </div>
</div>
<script>
  $('.bxslider').bxSlider({
    infiniteLoop: true,
    auto: true,
    pause: 3000,
    useCSS: false,
    autoHover: true,
    controls: false
  });

  $(".fancybox").fancybox();
</script>