config/routes.rb
Rails.application.routes.draw do

  resources :widgets

  get '/party/:id', :to => "rooms#party", :as => :party

  post '/rate' => 'rater#create', :as => 'rate'
  root :to => 'home#index'
  resources :carts, :home, :categories, :banners, :orders, :rooms

  resources :products do
    resources :images do
      collection do
        get :image_destroy
      end
    end
    resources :reviews
    resources :videos do
      collection do
        get :video_destroy
      end
    end
    member do
      get :add_to_cart
    end
  end

  resources :conversations do
    resources :chats
  end

  resources :messages do
    collection do
      get :inbox, :outbox
    end
  end
  devise_for :users

  get '/setting/:id' => 'home#setting', :as => :setting
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/contact_us' => 'home#contact_us', :as => :contact_us
  get '/services' => 'home#services', :as => :services
  put '/update_setting/:id' => 'home#update_setting', :as => :update_setting
  put '/change_password/:id' => 'home#change_password', :as => :change_password
  get '/order/express' => 'orders#express', :as => :pay
  post '/payu_callback'=>'carts#payu_return'

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  has_many :images, :as => :imageable
  accepts_nested_attributes_for :images, :allow_destroy => true, :reject_if => :all_blank
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :image, :styles => {:thumb => '90*90>', :large => '180*180>'}
  validates :image, :presence => true
  validates_attachment_content_type :image,
    :content_type => [ 'image/jpeg','image/jpg', 'image/png', 'image/gif','image/bmp', 'image/x-png', 'image/pjpeg' ]
  belongs_to :imageable, :polymorphic => true
  crop_attached_file :image

  def to_file_upload
    {
      "url" => image.url,
      "thumbnail_url" => image.url(:large)
    }
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @product = Product.find(params[:product_id])
    @images = @product.images.all
  end

  def new
    @product = Product.find(params[:product_id])
    @image = @product.images.new
  end

  def create
    @product = Product.find(params[:product_id])
    @image = @product.images.new(new_params)
    if @image.save
      render json: { message: "success" }, :status => 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, :status => 400
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @image = Image.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @image = Image.find(params[:id])
    if @image.update_attributes(new_params)
      redirect_to product_images_path(@product)
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @image = Image.find(params[:id])
    @images = @product.images.all
    @image.destroy
    respond_format
  end

  def image_destroy
    @product = Product.find(params[:product_id])
    if params[:image_ids].present?
      @images = Image.find(params[:image_ids])
      for image in @images
        image.destroy
      end
    end
    redirect_to product_images_path(@product)
  end

  private

  def new_params
    params.require(:image).permit!
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_images.html.erb
<div class="row">
  <% for image in @images %>
    <div class="col-sm-4 col-lg-3 col-md-4">
      <div class="thumbnail">
        <span id="product_img"><%= link_to image_tag(image.image.url(:original), :height => 185, :width => 185, :id => "image_#{image.id}"), "#{image.image.url}", :title => "#{image.image_file_name}", :class => 'fancybox', :rel => "gallery1"  %></span>
        <div class="ratings">
          <% if current_user %>
            <hr />
            <p>
            <div class="checkbox checkbox-danger checkbox-inline">
              <%= check_box_tag 'image_ids[]', image[:id], false,:class => 'check_all' %>
              <label for="checkbox6"></label>
            </div>|
            <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_product_image_path(image.imageable, image) %> |
            <%= link_to image_tag("rotate.jpeg"), "#", :class => "item-3", :id => "rotate_#{image.id}", :title => 'rotate' %> |
            <%= link_to "<i class='fa fa-trash-o'></i>".html_safe, product_image_path(image.imageable,image), :method => :delete, :data => { :confirm => 'Are you sure?'}, :remote => true %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <script>
      var value_<%= image.id %> = 0
      $("#rotate_<%= image.id %>").click(function() {
        value_<%= image.id %> += 90;
        $("#image_<%= image.id %>").rotate({animateTo: value_<%= image.id %>})
      });
    </script>
  <% end %>
</div>

app/views/images/destroy.js.erb
$("#product_images").html('<%= escape_javascript render :partial => "images" %>');

app/views/images/edit.html.erb
<%= form_for @image, :url => product_image_path(@product, @image), :method => 'PUT' do |f| %>
  <h3>Crop Image
    <%= f.submit 'Save', :class => 'btn btn-xs btn-success', :style => "float: right;" %>
  </h3>
  <hr />
  <%= f.cropbox :image, :width => 300 %>
  <%= f.crop_preview :image, :width => 150 %>
  <br />
<% end %>

app/views/images/index.html.erb
<%= form_tag image_destroy_product_images_path(@product), :method => :get do %>
  <h3>
    Product Images
    <div class="pull-right">
      <div class="checkbox checkbox-danger checkbox-inline">
        <input type="checkbox" id="selecctall" />
        <label for="inlineCheckbox2"></label>
      </div>
      <%= submit_tag "delete all", :class => "btn btn-xs btn-danger" %>
      <%= link_to "Add Images", new_product_image_path(@product), :class => 'btn btn-success btn-xs' %>
    </div>
  </h3>
  <hr />
  <div id="product_images">
    <%= render :partial => 'images' %>
  </div>
<% end %>
<script>
  $(".fancybox").fancybox();

  $("#selecctall").change(function() {
    $(".check_all").prop('checked', $(this).prop("checked"));
  });
</script>

app/views/images/new.html.erb
<h3>Upload Images
  <%= link_to "Product Images", product_images_path(@product), :class => 'btn btn-success btn-xs', :style => 'float: right;' %>
</h3>
<hr />
<%= form_for @image, :url => product_images_path(@product), :method => 'POST', html: { multipart: true, class: "dropzone"} do |f|  %>
    <div class="fallback">
      <%= f.file_field :image %><br>
      <%= f.submit "Upload" %>
    </div>
  <% end %>
  <br>
  <script>
    $(document).ready(function() {
      // disable auto discover
      Dropzone.autoDiscover = true;

      // grap our upload form by its id
      $("#new_image").dropzone({
        // restrict image size to a maximum 1MB
        maxFilesize: 1,
        // changed the passed param to one accepted by
        // our rails app
        paramName: "image[image]",
        addRemoveLinks: true
      });
    });
  </script>